import MainLayout from "@/modules/layouts/MainLayout/MainLayout";
import type { Metadata } from "next";
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
}
