import MainLayout from "@/modules/layouts/MainLayout/MainLayout";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get(process.env.NEXT_PUBLIC_TOKEN_KEY!);
  if (!token) return redirect(`en/auth/login`)
  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
}
